# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asset/LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoginUI(QtWidgets.QMainWindow):
    def __init__(self):
        super(LoginUI, self).__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 430)
        MainWindow.setStyleSheet("background-color:rgb(40, 40, 40)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(69, 139, 351, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("font:120 18pt \"Anonymous Pro for Powerline\";"
        "color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font:120 18pt \"Anonymous Pro for Powerline\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        # add password enter
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        # self.lineEdit.setPlaceholderText("Please enter User ID")
        # self.lineEdit_2.setPlaceholderText("Please enter Password")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 330, 351, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton{font: 400 20pt \"Anonymous Pro for Powerline\";\n"
        "border-radius:6px;background-color:rgb(100, 100, 100);color:rgb(255, 255, 255);\n}"
        "QPushButton:pressed{background-color:rgb(134, 134, 134);padding-left:2px;padding-top:2px;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton{font: 400 20pt \"Anonymous Pro for Powerline\";\n"
        "background-color:rgb(52, 117, 210);;\n"
        "color:rgb(255, 255, 255);\n"
        "border-radius:6px;}\n"
        "QPushButton:pressed{padding-left:2px;padding-top:2px;background-color:rgb(73, 153, 230);}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 341, 81))
        self.label_3.setStyleSheet("font:1500 40pt \"Anonymous Pro for Powerline\";"
        "color:rgb(255, 255, 255);\n")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log In"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">User ID</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Password</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Sign In"))
        self.pushButton.setText(_translate("MainWindow", "Sign Up"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TEXT READER</p></body></html>"))

        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myui = LoginUI()
    myui.show()
    sys.exit(app.exec_())